##Trying to find the best model for assessment

In [2]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
%matplotlib inline

In [3]:
iris_data = load_iris()
dir(iris_data)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

##Logistic Regression

In [4]:
LG_score = cross_val_score(LogisticRegression(max_iter=150),iris_data.data ,iris_data.target )
LG_score


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [7]:
np.average(LG_score)

0.9733333333333334

##Support Vector Machine (SVM)

In [6]:
svm_score = cross_val_score(SVC(),iris_data.data ,iris_data.target )
svm_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [35]:
np.average(svm_score)

0.9666666666666666

##Random Forest

In [8]:
rf_score = cross_val_score(RandomForestClassifier(n_estimators=5),iris_data.data ,iris_data.target )
rf_score

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [9]:
np.average(rf_score)

0.9600000000000002

##Decision Tree

In [10]:
dt_score = cross_val_score(DecisionTreeClassifier(),iris_data.data ,iris_data.target )
dt_score

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [11]:
np.average(dt_score)

0.9533333333333334